tenant:
  hostname: "test381170.a-vir-r1.int.ipaas.automation.ibm.com"   # webMethodsIO Integration hostname or ip address
  port: "443"                                       # webMethodsIO Integration port
  X-INSTANCE-API-KEY: "X-INSTANCE-API-KEY"     # webMethodsIO Integration API Key (Gen-2)
  type: "dev"                                         #DEV